---
version: '2.0'
services:
  shad-staker-nginx:
    image: 'antonymousn/shad-staker:nginx-test-1'
    expose:
      - port: 80
        as: 80
        to:
          - global: true
profiles:
  compute:
    shad-staker-nginx:
      resources:
        cpu:
          units: 0.5
        memory:
          size: 1Gi
        storage:
          - size: 1Gi
  placement:
    dcloud:
      pricing:
        shad-staker-nginx:
          denom: uakt
          amount: 1000
deployment:
  shad-staker-nginx:
    dcloud:
      profile: shad-staker-nginx
      count: 1
